### PR TITLE
rework & test ReceiveStream

### PR DESCRIPTION
**Pull request by WebFreak001**
* it is now an interface allowing for more than just an std.socket implementation (renamed to SocketReceiveStream : IReceiveStream)
* moved all the reading methods into one powerful, more efficient reading method which can use the buffer both after bufferPos and before bufferPos
* added unittest testing that wrapping around and large byte receiving actually works
* fix readCharsWithLengthPrefix (it allows 0 characters inside it)
* use appender to build large chunks, allocate in one go and use std.bitmanip for conversion to common types

Overall improves memory efficiency and bandwidth usage

### CODE REVIEW

**Comment by WebFreak001** [comment]
more specifically about the change from class to interface: I want to later add support using vibe-core TCP streams so this can be used as replacement to the vibe.d MongoDB driver (which has quite a lot of legacy stuff) and the interface implementer just needs to implement a simple receive bytes method

**Comment by adamdruppe** [comment]
OK yeah, that makes sense.

Fun story about me writing this: at first I was going to do some fancy introspection reader (that's why there's the struct OP_X definitions though they are never used elsewhere) and did the stream class just to simplify that but then found the plain old methods were easier to use anyway. The code ended up looking kinda java-ish with visitors and named methods but I'm actually pretty happy with it for the most part. My favorite part about D is its flexibility is just letting all these styles work well.

**Comment by WebFreak001** [comment]
a fancy introspection reader could still be added here, I just abstracted away the read bytes methods, made the primitive read functions use them and moved all the existing functions into the interface as final function to preserve basic backwards compatibility (though it would break if someone had inherited the class and modified the parse methods)

**Comment by adamdruppe** [comment]
BTW on vibe, actually a reason this exists in the first place was to avoid bringing in any vibe deps, so that would surely have to be in a different module. Perhaps the stream could be passed to an overloaded constructor thanks to the interface to keep dependency isolated (and then dub config stuff too to avoid the dependency from coming in without the specific opt in)

**Comment by WebFreak001** [comment]
dub supports optional dependencies, which you can check in code like `version (Have_vibe_core)` and if the depender depends on them, this library will have access to it too

**Pull request merged**
