### PR TITLE
fix license identifier in dub & add LICENSE file

### PR DESCRIPTION
**Pull request by WebFreak001**
assumes Boost license meant the BSL v1

The LICENSE file makes it visible on github

For license identifiers see https://dub.pm/package-format-json.html#licenses

### CODE REVIEW

**Comment by adamdruppe** [comment]
i need to hold on this cuz it might actually be BSD instead due to me copy/pasting that bsd'd bit from Vibe and including it here.

**Comment by WebFreak001** [comment]
the vibe bit is MIT according to comment header

**Comment by adamdruppe** [comment]
oh yeah that's what i meant my brain jsut jumbles bsd and mit together. But  I'll prolly go with that.....

**Comment by adamdruppe** [comment]
gonna close cuz i pushed up the mit one instead to be fully compatible with the bit copied from vibe.

**Pull request closed without merging**
